IF
	!GlobalTimerNotExpired("RR#fusion","LOCALS")
	Global("RR#jelly_no_fusion","LOCALS",0)
	HitBy([ANYONE],FIRE)
THEN
	RESPONSE #100
		SetGlobal("RR#jelly_no_fusion","LOCALS",1)
        SetGlobalTimer("RR#fusion","LOCALS",12)
END

IF
	Global("RR#jelly_no_fusion","LOCALS",0)
	HitBy([ANYONE],0)
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		DisplayStringHead(Myself,71108)  // Rather than dying, the creature splits into two.
		DestroySelf()
		CreateCreatureObjectEffect("SLIFIS02","TRGOOYBB",Myself)  // Fission Slime 
		CreateCreatureObjectEffect("SLIFIS02","TRGOOYBB",Myself)  // Fission Slime
		SetInterrupt(TRUE)
END

IF
    Global("RR#Active","LOCALS",0)
    Allegiance(Myself,EVILCUTOFF)
    See([GOODCUTOFF]) // this cannot be in the previous block, otherwise neutral creatures would go hostile upon seeing a party member
THEN
    RESPONSE #100
        SetGlobal("RR#Active","LOCALS",1)
        SetGlobalTimer("RR#Rest","LOCALS",2400) // 8 hours
        Enemy()
END

IF
!Detect(NearestEnemyOf(Myself))
Global("RR#Rest","LOCALS",1)
!GlobalTimerNotExpired("RR#RestTimer","LOCALS")
THEN
RESPONSE #100
SetGlobal("RR#Rest","LOCALS",0)
ApplySpell(Myself,RESTORE_FULL_HEALTH)
Rest()
END

IF
!GlobalTimerNotExpired("RR#RestTimer","LOCALS")
Detect(NearestEnemyOf(Myself))
Global("RR#Rest","LOCALS",0)
THEN
RESPONSE #100
SetGlobalTimer("RR#RestTimer","LOCALS",2400)
SetGlobal("RR#Rest","LOCALS",1)
Continue()
END

IF
OR(13)
HitBy([GOODCUTOFF],0)
AttackedBy([GOODCUTOFF.0.0.0.0.SUMMONED],DEFAULT)
AttackedBy([PC],DEFAULT)
AttackedBy([FAMILIAR],DEFAULT)
AttackedBy([ALLY],DEFAULT)
AttackedBy([CONTROLLED],DEFAULT)
AttackedBy([CHARMED],DEFAULT)
SpellCastOnMe([GOODCUTOFF.0.0.0.0.SUMMONED],0)
SpellCastOnMe([PC],0)
SpellCastOnMe([FAMILIAR],0)
SpellCastOnMe([ALLY],0)
SpellCastOnMe([CONTROLLED],0)
SpellCastOnMe([CHARMED],0)
!GlobalTimerNotExpired("whatthe","LOCALS")
!See([GOODCUTOFF])
THEN
RESPONSE #100
Enemy()
SetGlobalTimer("whatthe","LOCALS",12)
Continue()
END

IF
!See([GOODCUTOFF])
GlobalTimerNotExpired("whatthe","LOCALS")
THEN
RESPONSE #100
RandomWalkContinuous()
END

IF
See([GOODCUTOFF])
GlobalTimerNotExpired("whatthe","LOCALS")
THEN
RESPONSE #100
ClearActions(Myself)
SetGlobalTimer("whatthe","LOCALS",0)
END

// IF
// StateCheck(Myself,STATE_PANIC)
// THEN
// RESPONSE #100
// RandomWalkContinuous()
// END

// IF
// StateCheck(Myself,STATE_CHARMED)
// See(NearestEnemyOf(Myself))
// ActionListEmpty()
// Range(LastSeenBy(Myself),5)
// THEN
// RESPONSE #100
// Attack(LastSeenBy(Myself))
// END

IF
See(NearestEnemyOf(Myself))
Range(NearestEnemyOf(Myself),5)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
See(SecondNearestEnemyOf(Myself))
Range(SecondNearestEnemyOf(Myself),5)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(SecondNearestEnemyOf(Myself),30)
END

IF
See(ThirdNearestEnemyOf(Myself))
Range(ThirdNearestEnemyOf(Myself),5)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(ThirdNearestEnemyOf(Myself),30)
END

IF
See(FourthNearestEnemyOf(Myself))
Range(FourthNearestEnemyOf(Myself),5)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(FourthNearestEnemyOf(Myself),30)
END

IF
See(FifthNearestEnemyOf(Myself))
Range(FifthNearestEnemyOf(Myself),5)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(FifthNearestEnemyOf(Myself),30)
END

IF
See(SixthNearestEnemyOf(Myself))
Range(SixthNearestEnemyOf(Myself),5)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(SixthNearestEnemyOf(Myself),30)
END

IF
ActionListEmpty()
See(NearestEnemyOf(Myself))
Allegiance(Myself,EVILCUTOFF)
THEN
RESPONSE #100
MoveToObject(NearestEnemyOf(Myself))
END

IF
ActionListEmpty()
See(SecondNearestEnemyOf(Myself))
Allegiance(Myself,EVILCUTOFF)
THEN
RESPONSE #100
MoveToObject(SecondNearestEnemyOf(Myself))
END

IF
ActionListEmpty()
See(ThirdNearestEnemyOf(Myself))
Allegiance(Myself,EVILCUTOFF)
THEN
RESPONSE #100
MoveToObject(ThirdNearestEnemyOf(Myself))
END

IF
ActionListEmpty()
See(FourthNearestEnemyOf(Myself))
Allegiance(Myself,EVILCUTOFF)
THEN
RESPONSE #100
MoveToObject(FourthNearestEnemyOf(Myself))
END

IF
ActionListEmpty()
See(FifthNearestEnemyOf(Myself))
Allegiance(Myself,EVILCUTOFF)
THEN
RESPONSE #100
MoveToObject(FifthNearestEnemyOf(Myself))
END

IF
ActionListEmpty()
See(SixthNearestEnemyOf(Myself))
Allegiance(Myself,EVILCUTOFF)
THEN
RESPONSE #100
MoveToObject(SixthNearestEnemyOf(Myself))
END

IF
See(NearestEnemyOf(Myself))
ActionListEmpty()
Allegiance(Myself,EVILCUTOFF)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(NearestEnemyOf(Myself),30)
END

IF
See(LastAttackerOf(Myself))
ActionListEmpty()
!Allegiance(Myself,ENEMY)
AttackedBy([ANYONE],DEFAULT)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(LastAttackerOf(Myself),30)
END