
////////////////////////////////////////////////
// Make alignment detection spells more accurate
////////////////////////////////////////////////


COPY    ~aTweaks/EFF/RR#DAGLR.EFF~ ~override~                                      // Red glow (for evil aligned creatures)
COPY    ~aTweaks/EFF/RR#DAGLG.EFF~ ~override~                                      // Green glow (for good aligned creatures)
COPY    ~aTweaks/EFF/RR#DAGLB.EFF~ ~override~                                      // Blue glow (for neutral aligned creatures)
COPY    ~aTweaks/EFF/RR#DASLG.EFF~ ~override~                                      // Display String: Lawful Good
COPY    ~aTweaks/EFF/RR#DASLE.EFF~ ~override~                                      // Display String: Lawful Evil
COPY    ~aTweaks/EFF/RR#DASLN.EFF~ ~override~                                      // Display String: Lawful Neutral
COPY    ~aTweaks/EFF/RR#DASNG.EFF~ ~override~                                      // Display String: Neutral Good
COPY    ~aTweaks/EFF/RR#DASNE.EFF~ ~override~                                      // Display String: Neutral Evil
COPY    ~aTweaks/EFF/RR#DASNT.EFF~ ~override~                                      // Display String: True Neutral
COPY    ~aTweaks/EFF/RR#DASCG.EFF~ ~override~                                      // Display String: Chaotic Good
COPY    ~aTweaks/EFF/RR#DASCE.EFF~ ~override~                                      // Display String: Chaotic Evil
COPY    ~aTweaks/EFF/RR#DASCN.EFF~ ~override~                                      // Display String: Chaotic Neutral


// Detect Evil

ACTION_FOR_EACH ~file~ IN                                                          // for each of the following files
              ~SPPR104~                                                            // Detect Evil (Divine version)
              ~SPWI202~                                                            // Detect Evil (Arcane version)
              ~SPCL212~                                                            // Detect Evil (Paladin innate)
              ~SPIN696~                                                            // Moon Dog Sight (Moon Dog figurine)
             ~CDDETEVL~                                                            // G3 BG2 Fixpack Detect Evil (shell spell)
BEGIN                                                                              // execute the following
ACTION_IF FILE_EXISTS_IN_GAME ~%file%.spl~ BEGIN                                   // if the designated file with a SPL extension exists
COPY_EXISTING ~%file%.spl~ ~override~
PATCH_IF (%SOURCE_SIZE% > 0x71) THEN BEGIN                                         // file size check
// =============================================================================== // the actual work starts from here
  LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode = 115 opcode = 177 parameter1 = 3 parameter2 = 8 timing = 0 duration = 1 STR_VAR resource ="RR#DAGLR" END
  LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode = 177 parameter1 = 19 timing = 0 duration = 1 STR_VAR resource ="RR#DASLE" END
  LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode = 177 parameter1 = 35 timing = 0 duration = 1 STR_VAR match_resource = "RR#DAGLR" resource ="RR#DASNE" END
  LPF CLONE_EFFECT INT_VAR silent = 1 match_opcode = 177 parameter1 = 51 timing = 0 duration = 1 STR_VAR match_resource = "RR#DAGLR" resource ="RR#DASCE" END
  LPF DELETE_EFFECT STR_VAR silent = 1 match_opcode = 115 END
// =============================================================================== // the actual work ends here
END                                                                                // ends file size check
BUT_ONLY_IF_IT_CHANGES
END                                                                                // ends ACTION_IF FILE_EXISTS_IN_GAME block
END                                                                                // ends ACTION_FOR_EACH block

// Detect good
OUTER_SPRINT DetectG ""
ACTION_IF IDS_OF_SYMBOL ("spell" "CLERIC_DETECT_GOOD") > 0 BEGIN 
 OUTER_SET code = (IDS_OF_SYMBOL ("spell" "CLERIC_DETECT_GOOD") - 1000)
 OUTER_SPRINT "DetectG" "SPPR%code%"
END

ACTION_FOR_EACH ~file~ IN                                                          // for each of the following files
			  ~WTPIN02B~														   // WTP Find Familliar
              ~%DetectG%~														   // Divine Remix
BEGIN                                                                              // execute the following
ACTION_IF FILE_EXISTS_IN_GAME ~%file%.spl~ BEGIN                                   // if the designated file with a SPL extension exists
COPY_EXISTING ~%file%.spl~ ~override~
PATCH_IF (%SOURCE_SIZE% > 0x71) THEN BEGIN                                         // file size check
// =============================================================================== // the actual work starts from here
  LPF CLONE_EFFECT INT_VAR match_opcode = 115 opcode = 177 parameter1 = 1 parameter2 = 8 timing = 0 duration = 1 STR_VAR resource ="RR#DAGLG" END
  LPF CLONE_EFFECT INT_VAR match_opcode = 177 parameter1 = 17 timing = 0 duration = 1 STR_VAR resource ="RR#DASLG" END
  LPF CLONE_EFFECT INT_VAR match_opcode = 177 parameter1 = 33 timing = 0 duration = 1 STR_VAR match_resource = "RR#DAGLG" resource ="RR#DASNG" END
  LPF CLONE_EFFECT INT_VAR match_opcode = 177 parameter1 = 49 timing = 0 duration = 1 STR_VAR match_resource = "RR#DAGLG" resource ="RR#DASCG" END
  LPF DELETE_EFFECT STR_VAR match_opcode = 115 END
// =============================================================================== // the actual work ends here
END                                                                                // ends file size check
BUT_ONLY_IF_IT_CHANGES
END                                                                                // ends ACTION_IF FILE_EXISTS_IN_GAME block
END                                                                                // ends ACTION_FOR_EACH block


ACTION_IF (NOT MOD_IS_INSTALLED SPELL_REV.TP2 0) AND (NOT MOD_IS_INSTALLED SETUP-OVERSIGHT.TP2 3) THEN BEGIN  // Checks for the main component of Spell Revisions and for the Altered Spells component of Oversight

// Know Alignment

ACTION_FOR_EACH ~file~ IN                                                          // for each of the following files
              ~SPPR209~                                                            // Know Alignment (Divine version)
              ~SPWI208~                                                            // Know Alignment (Arcane version)
             ~RR#WI208~                                                            // Know Alignment (RR version used by Keeper of the Law)
              ~rr#ekal~                                                            // Know Alignment (aTweaks version used by the Elemental Princes)
              ~VXFI~                                                               // Know Alignment (varshoon: Feel Intensions)
BEGIN                                                                              // execute the following
ACTION_IF FILE_EXISTS_IN_GAME ~%file%.spl~ BEGIN                                   // if the designated file with a SPL extension exists
COPY_EXISTING ~%file%.spl~ ~override~
PATCH_IF (%SOURCE_SIZE% > 0x71) THEN BEGIN                                         // file size check
// =============================================================================== // the actual work starts from here
  LPF CLONE_EFFECT INT_VAR match_opcode = 115 match_parameter2 = 2 opcode = 177 parameter1 = 1 parameter2 = 8 timing = 0 duration = 1 STR_VAR resource ="RR#DAGLG" END
  LPF CLONE_EFFECT INT_VAR match_opcode = 177 parameter1 = 2 timing = 0 duration = 1 STR_VAR match_resource = "RR#DAGLG" resource ="RR#DAGLB" END
  LPF CLONE_EFFECT INT_VAR match_opcode = 177 parameter1 = 3 timing = 0 duration = 1 STR_VAR match_resource = "RR#DAGLG" resource ="RR#DAGLR" END
  LPF CLONE_EFFECT INT_VAR match_opcode = 177 parameter1 = 17 timing = 0 duration = 1 STR_VAR match_resource = "RR#DAGLG" resource ="RR#DASLG" END
  LPF CLONE_EFFECT INT_VAR match_opcode = 177 parameter1 = 18 timing = 0 duration = 1 STR_VAR match_resource = "RR#DAGLG" resource ="RR#DASLN" END
  LPF CLONE_EFFECT INT_VAR match_opcode = 177 parameter1 = 19 timing = 0 duration = 1 STR_VAR match_resource = "RR#DAGLG" resource ="RR#DASLE" END
  LPF CLONE_EFFECT INT_VAR match_opcode = 177 parameter1 = 33 timing = 0 duration = 1 STR_VAR match_resource = "RR#DAGLG" resource ="RR#DASNG" END
  LPF CLONE_EFFECT INT_VAR match_opcode = 177 parameter1 = 34 timing = 0 duration = 1 STR_VAR match_resource = "RR#DAGLG" resource ="RR#DASNT" END
  LPF CLONE_EFFECT INT_VAR match_opcode = 177 parameter1 = 35 timing = 0 duration = 1 STR_VAR match_resource = "RR#DAGLG" resource ="RR#DASNE" END
  LPF CLONE_EFFECT INT_VAR match_opcode = 177 parameter1 = 49 timing = 0 duration = 1 STR_VAR match_resource = "RR#DAGLG" resource ="RR#DASCG" END
  LPF CLONE_EFFECT INT_VAR match_opcode = 177 parameter1 = 50 timing = 0 duration = 1 STR_VAR match_resource = "RR#DAGLG" resource ="RR#DASCN" END
  LPF CLONE_EFFECT INT_VAR match_opcode = 177 parameter1 = 51 timing = 0 duration = 1 STR_VAR match_resource = "RR#DAGLG" resource ="RR#DASCE" END
  LPF DELETE_EFFECT STR_VAR match_opcode = 115 END
  LPF DELETE_EFFECT STR_VAR match_opcode = 139 END
// =============================================================================== // the actual work ends here
END                                                                                // ends file size check
BUT_ONLY_IF_IT_CHANGES
END                                                                                // ends ACTION_IF FILE_EXISTS_IN_GAME block
END                                                                                // ends ACTION_FOR_EACH block

END                                                                                // ends check for Spell Revisions and Oversight


// Special Spell Revisions compatibility block

ACTION_IF MOD_IS_INSTALLED SPELL_REV.TP2 0 THEN BEGIN                              // SR's Detect Alignment needs special treatment
COPY_EXISTING ~SPWI202.SPL~  ~override~                                            // Detect Alignment (Arcane version)
			  ~SPPR104.SPL~  ~override~                                            // Detect Alignment (Divine version)
// =============================================================================== // the actual work starts from here
  LPF CLONE_EFFECT INT_VAR match_opcode = 177 parameter1 = 2 timing = 0 duration = 1 STR_VAR match_resource = "RR#DAGLR" resource ="RR#DAGLG" END
  LPF CLONE_EFFECT INT_VAR match_opcode = 177 parameter1 = 2 timing = 0 duration = 1 STR_VAR match_resource = "RR#DAGLR" resource ="RR#DAGLB" END
  LPF CLONE_EFFECT INT_VAR match_opcode = 177 parameter1 = 3 timing = 0 duration = 1 STR_VAR match_resource = "RR#DAGLR" resource ="RR#DAGLR" END
  LPF CLONE_EFFECT INT_VAR match_opcode = 177 parameter1 = 17 timing = 0 duration = 1 STR_VAR match_resource = "RR#DAGLR" resource ="RR#DASLG" END
  LPF CLONE_EFFECT INT_VAR match_opcode = 177 parameter1 = 18 timing = 0 duration = 1 STR_VAR match_resource = "RR#DAGLR" resource ="RR#DASLN" END
  LPF CLONE_EFFECT INT_VAR match_opcode = 177 parameter1 = 33 timing = 0 duration = 1 STR_VAR match_resource = "RR#DAGLR" resource ="RR#DASNG" END
  LPF CLONE_EFFECT INT_VAR match_opcode = 177 parameter1 = 34 timing = 0 duration = 1 STR_VAR match_resource = "RR#DAGLR" resource ="RR#DASNT" END
  LPF CLONE_EFFECT INT_VAR match_opcode = 177 parameter1 = 49 timing = 0 duration = 1 STR_VAR match_resource = "RR#DAGLR" resource ="RR#DASCG" END
  LPF CLONE_EFFECT INT_VAR match_opcode = 177 parameter1 = 50 timing = 0 duration = 1 STR_VAR match_resource = "RR#DAGLR" resource ="RR#DASCN" END
// =============================================================================== // the actual work ends here
BUT_ONLY_IF_IT_CHANGES

END                                                                                // ends SR compatibility block

