IF
Global("RR#Active","LOCALS",0)
OR(2)
AttackedBy([ANYONE],DEFAULT)
TookDamage()
THEN
RESPONSE #100
SetGlobal("RR#Active","LOCALS",1)
SetGlobalTimer("RR#Rest","LOCALS",2400) // 8 hours
Enemy()
Continue()
END

IF
Global("RR#Active","LOCALS",0)
Allegiance(Myself,EVILCUTOFF)
See([GOODCUTOFF]) // this cannot be in the previous block, otherwise neutral creatures would go hostile upon seeing a party member
THEN
RESPONSE #100
SetGlobal("RR#Active","LOCALS",1)
SetGlobalTimer("RR#Rest","LOCALS",2400) // 8 hours
Enemy()
Continue()
END

IF
	!GlobalTimerNotExpired("RR#Help","LOCALS") // shout for help every two rounds while in combat, others may hear it and join the battle
	Allegiance(Myself,EVILCUTOFF)
	See([GOODCUTOFF])
THEN
	RESPONSE #100
		SetGlobalTimer("RR#Help","LOCALS",12)
				Continue()
END

IF
!Detect(NearestEnemyOf(Myself))
Global("RR#Rest","LOCALS",1)
!GlobalTimerNotExpired("RR#RestTimer","LOCALS")
THEN
RESPONSE #100
SetGlobal("RR#Rest","LOCALS",0)
ApplySpell(Myself,RESTORE_FULL_HEALTH)
Rest()
END

IF
!GlobalTimerNotExpired("RR#RestTimer","LOCALS")
Detect(NearestEnemyOf(Myself))
Global("RR#Rest","LOCALS",0)
THEN
RESPONSE #100
SetGlobalTimer("RR#RestTimer","LOCALS",2400)
SetGlobal("RR#Rest","LOCALS",1)
Continue()
END

IF
Global("RR#Active","LOCALS",0)
HitBy([GOODCUTOFF],0)
!Allegiance(Myself,GOODCUTOFF)
THEN
RESPONSE #100
SetGlobal("RR#Active","LOCALS",1)
Enemy()
Continue()
END

IF
Global("RR#Active","LOCALS",0)
Allegiance(Myself,EVILCUTOFF)
See([GOODCUTOFF])
THEN
RESPONSE #100
SetGlobal("RR#Active","LOCALS",1)
Continue()
END

IF
OR(13)
HitBy([GOODCUTOFF],0)
AttackedBy([GOODCUTOFF.0.0.0.0.SUMMONED],DEFAULT)
AttackedBy([PC],DEFAULT)
AttackedBy([FAMILIAR],DEFAULT)
AttackedBy([ALLY],DEFAULT)
AttackedBy([CONTROLLED],DEFAULT)
AttackedBy([CHARMED],DEFAULT)
SpellCastOnMe([GOODCUTOFF.0.0.0.0.SUMMONED],0)
SpellCastOnMe([PC],0)
SpellCastOnMe([FAMILIAR],0)
SpellCastOnMe([ALLY],0)
SpellCastOnMe([CONTROLLED],0)
SpellCastOnMe([CHARMED],0)
!GlobalTimerNotExpired("whatthe","LOCALS")
!See([GOODCUTOFF])
THEN
RESPONSE #100
Enemy()
SetGlobalTimer("whatthe","LOCALS",12)
Continue()
END

IF
!See([GOODCUTOFF])
GlobalTimerNotExpired("whatthe","LOCALS")
THEN
RESPONSE #100
RandomWalkContinuous()
END

IF
See([GOODCUTOFF])
GlobalTimerNotExpired("whatthe","LOCALS")
THEN
RESPONSE #100
ClearActions(Myself)
SetGlobalTimer("whatthe","LOCALS",0)
END

IF
Allegiance(Myself,EVILCUTOFF)
Global("RR#Active","LOCALS",0)
!Detect(NearestEnemyOf(Myself))
THEN
RESPONSE #100
NoAction()
END

IF
StateCheck(Myself,STATE_PANIC)
THEN
RESPONSE #100
RandomWalkContinuous()
END

IF
StateCheck(Myself,STATE_CHARMED)
See(NearestEnemyOf(Myself))
!Range(LastSeenBy(Myself),5)
THEN
RESPONSE #100
MoveToObject(LastSeenBy(Myself))
END

IF
StateCheck(Myself,STATE_CHARMED)
See(NearestEnemyOf(Myself))
Range(LastSeenBy(Myself),5)
THEN
RESPONSE #100
Attack(LastSeenBy(Myself))
END

IF
SpellCast([ANYONE],WIZARD_WEB)
See(NearestEnemyOf(Myself))
THEN
RESPONSE #100
SetGlobalTimer("rr#web","LOCALS",30)  // web refresh timer
Continue()
END

IF
	HaveSpellRES("rr#spwr2")
    !GlobalTimerNotExpired("rr#web","LOCALS") // Web refresh timer
	OR(3)
	See([EVILCUTOFF.0.107])
	See([EVILCUTOFF.0.108])
	!See([EVILCUTOFF])
	See([GOODCUTOFF])
	!Race(LastSeenBy(Myself),ELEMENTAL)
	!Race(LastSeenBy(Myself),SHADOW)
	!Race(LastSeenBy(Myself),SPECTRE)
	!Race(LastSeenBy(Myself),MIST)
	!Race(LastSeenBy(Myself),WRAITH)
	!Race(LastSeenBy(Myself),SLIME)
	!Race(LastSeenBy(Myself),DRAGON)
	!Class(LastSeenBy(Myself),GIANT)
	!Class(LastSeenBy(Myself),GOLEM_IRON)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTCOLD)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)  // Spell Immunity: Alteration
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!CheckStatGT(LastSeenBy(Myself),0,WEB)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!Check%State%(LastSeenBy(Myself),%Num%ITEM_HOLD)
THEN
	RESPONSE #100
		SetGlobalTimer("rr#web","LOCALS",30)  // web refresh timer
        ReallyForceSpellRes("rr#spwr2",LastSeenBy(Myself))
		RemoveSpellRES("rr#spwr2") // remove one instance of the spell upon casting
END

IF
	HaveSpellRES("rr#spwr2")
    !GlobalTimerNotExpired("rr#web","LOCALS") // Web refresh timer
	OR(3)
	See([EVILCUTOFF.0.107])
	See([EVILCUTOFF.0.108])
	!See([EVILCUTOFF])
	See(SecondNearest([GOODCUTOFF]))
	!Race(LastSeenBy(Myself),ELEMENTAL)
	!Race(LastSeenBy(Myself),SHADOW)
	!Race(LastSeenBy(Myself),SPECTRE)
	!Race(LastSeenBy(Myself),MIST)
	!Race(LastSeenBy(Myself),WRAITH)
	!Race(LastSeenBy(Myself),SLIME)
	!Race(LastSeenBy(Myself),DRAGON)
	!Class(LastSeenBy(Myself),GIANT)
	!Class(LastSeenBy(Myself),GOLEM_IRON)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTCOLD)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)  // Spell Immunity: Alteration
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!CheckStatGT(LastSeenBy(Myself),0,WEB)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!Check%State%(LastSeenBy(Myself),%Num%ITEM_HOLD)
THEN
	RESPONSE #100
		SetGlobalTimer("rr#web","LOCALS",30)  // web refresh timer
        ReallyForceSpellRes("rr#spwr2",LastSeenBy(Myself))
		RemoveSpellRES("rr#spwr2") // remove one instance of the spell upon casting
END

IF
	HaveSpellRES("rr#spwr2")
    !GlobalTimerNotExpired("rr#web","LOCALS") // Web refresh timer
	OR(3)
	See([EVILCUTOFF.0.107])
	See([EVILCUTOFF.0.108])
	!See([EVILCUTOFF])
	See(ThirdNearest([GOODCUTOFF]))
	!Race(LastSeenBy(Myself),ELEMENTAL)
	!Race(LastSeenBy(Myself),SHADOW)
	!Race(LastSeenBy(Myself),SPECTRE)
	!Race(LastSeenBy(Myself),MIST)
	!Race(LastSeenBy(Myself),WRAITH)
	!Race(LastSeenBy(Myself),SLIME)
	!Race(LastSeenBy(Myself),DRAGON)
	!Class(LastSeenBy(Myself),GIANT)
	!Class(LastSeenBy(Myself),GOLEM_IRON)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTCOLD)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)  // Spell Immunity: Alteration
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!CheckStatGT(LastSeenBy(Myself),0,WEB)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!Check%State%(LastSeenBy(Myself),%Num%ITEM_HOLD)
THEN
	RESPONSE #100
		SetGlobalTimer("rr#web","LOCALS",30)  // web refresh timer
        ReallyForceSpellRes("rr#spwr2",LastSeenBy(Myself))
		RemoveSpellRES("rr#spwr2") // remove one instance of the spell upon casting
END

IF
	HaveSpellRES("rr#spwr2")
    !GlobalTimerNotExpired("rr#web","LOCALS") // Web refresh timer
	OR(3)
	See([EVILCUTOFF.0.107])
	See([EVILCUTOFF.0.108])
	!See([EVILCUTOFF])
	See(FourthNearest([GOODCUTOFF]))
	!Race(LastSeenBy(Myself),ELEMENTAL)
	!Race(LastSeenBy(Myself),SHADOW)
	!Race(LastSeenBy(Myself),SPECTRE)
	!Race(LastSeenBy(Myself),MIST)
	!Race(LastSeenBy(Myself),WRAITH)
	!Race(LastSeenBy(Myself),SLIME)
	!Race(LastSeenBy(Myself),DRAGON)
	!Class(LastSeenBy(Myself),GIANT)
	!Class(LastSeenBy(Myself),GOLEM_IRON)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTCOLD)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)  // Spell Immunity: Alteration
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!CheckStatGT(LastSeenBy(Myself),0,WEB)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!Check%State%(LastSeenBy(Myself),%Num%ITEM_HOLD)
THEN
	RESPONSE #100
		SetGlobalTimer("rr#web","LOCALS",30)  // web refresh timer
        ReallyForceSpellRes("rr#spwr2",LastSeenBy(Myself))
		RemoveSpellRES("rr#spwr2") // remove one instance of the spell upon casting
END

IF
	HaveSpellRES("rr#spwr2")
    !GlobalTimerNotExpired("rr#web","LOCALS") // Web refresh timer
	OR(3)
	See([EVILCUTOFF.0.107])
	See([EVILCUTOFF.0.108])
	!See([EVILCUTOFF])
	See(FifthNearest([GOODCUTOFF]))
	!Race(LastSeenBy(Myself),ELEMENTAL)
	!Race(LastSeenBy(Myself),SHADOW)
	!Race(LastSeenBy(Myself),SPECTRE)
	!Race(LastSeenBy(Myself),MIST)
	!Race(LastSeenBy(Myself),WRAITH)
	!Race(LastSeenBy(Myself),SLIME)
	!Race(LastSeenBy(Myself),DRAGON)
	!Class(LastSeenBy(Myself),GIANT)
	!Class(LastSeenBy(Myself),GOLEM_IRON)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTCOLD)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)  // Spell Immunity: Alteration
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!CheckStatGT(LastSeenBy(Myself),0,WEB)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!Check%State%(LastSeenBy(Myself),%Num%ITEM_HOLD)
THEN
	RESPONSE #100
		SetGlobalTimer("rr#web","LOCALS",30)  // web refresh timer
        ReallyForceSpellRes("rr#spwr2",LastSeenBy(Myself))
		RemoveSpellRES("rr#spwr2") // remove one instance of the spell upon casting
END

IF
	HaveSpellRES("rr#spwr2")
    !GlobalTimerNotExpired("rr#web","LOCALS") // Web refresh timer
	OR(3)
	See([EVILCUTOFF.0.107])
	See([EVILCUTOFF.0.108])
	!See([EVILCUTOFF])
	See(SixthNearest([GOODCUTOFF]))
	!Race(LastSeenBy(Myself),ELEMENTAL)
	!Race(LastSeenBy(Myself),SHADOW)
	!Race(LastSeenBy(Myself),SPECTRE)
	!Race(LastSeenBy(Myself),MIST)
	!Race(LastSeenBy(Myself),WRAITH)
	!Race(LastSeenBy(Myself),SLIME)
	!Race(LastSeenBy(Myself),DRAGON)
	!Class(LastSeenBy(Myself),GIANT)
	!Class(LastSeenBy(Myself),GOLEM_IRON)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTCOLD)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)  // Spell Immunity: Alteration
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!CheckStatGT(LastSeenBy(Myself),0,WEB)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!Check%State%(LastSeenBy(Myself),%Num%ITEM_HOLD)
THEN
	RESPONSE #100
		SetGlobalTimer("rr#web","LOCALS",30)  // web refresh timer
        ReallyForceSpellRes("rr#spwr2",LastSeenBy(Myself))
		RemoveSpellRES("rr#spwr2") // remove one instance of the spell upon casting
END

IF
	HaveSpellRES("rr#spwr2")
    !GlobalTimerNotExpired("rr#web","LOCALS") // Web refresh timer
	OR(3)
	See([EVILCUTOFF.0.107])
	See([EVILCUTOFF.0.108])
	!See([EVILCUTOFF])
	See(SeventhNearest([GOODCUTOFF]))
	!Race(LastSeenBy(Myself),ELEMENTAL)
	!Race(LastSeenBy(Myself),SHADOW)
	!Race(LastSeenBy(Myself),SPECTRE)
	!Race(LastSeenBy(Myself),MIST)
	!Race(LastSeenBy(Myself),WRAITH)
	!Race(LastSeenBy(Myself),SLIME)
	!Race(LastSeenBy(Myself),DRAGON)
	!Class(LastSeenBy(Myself),GIANT)
	!Class(LastSeenBy(Myself),GOLEM_IRON)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTCOLD)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)  // Spell Immunity: Alteration
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!CheckStatGT(LastSeenBy(Myself),0,WEB)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!Check%State%(LastSeenBy(Myself),%Num%ITEM_HOLD)
THEN
	RESPONSE #100
		SetGlobalTimer("rr#web","LOCALS",30)  // web refresh timer
        ReallyForceSpellRes("rr#spwr2",LastSeenBy(Myself))
		RemoveSpellRES("rr#spwr2") // remove one instance of the spell upon casting
END

IF
	HaveSpellRES("rr#spwr2")
    !GlobalTimerNotExpired("rr#web","LOCALS") // Web refresh timer
	OR(3)
	See([EVILCUTOFF.0.107])
	See([EVILCUTOFF.0.108])
	!See([EVILCUTOFF])
	See(EighthNearest([GOODCUTOFF]))
	!Race(LastSeenBy(Myself),ELEMENTAL)
	!Race(LastSeenBy(Myself),SHADOW)
	!Race(LastSeenBy(Myself),SPECTRE)
	!Race(LastSeenBy(Myself),MIST)
	!Race(LastSeenBy(Myself),WRAITH)
	!Race(LastSeenBy(Myself),SLIME)
	!Race(LastSeenBy(Myself),DRAGON)
	!Class(LastSeenBy(Myself),GIANT)
	!Class(LastSeenBy(Myself),GOLEM_IRON)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTCOLD)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)  // Spell Immunity: Alteration
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!CheckStatGT(LastSeenBy(Myself),0,WEB)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!Check%State%(LastSeenBy(Myself),%Num%ITEM_HOLD)
THEN
	RESPONSE #100
		SetGlobalTimer("rr#web","LOCALS",30)  // web refresh timer
        ReallyForceSpellRes("rr#spwr2",LastSeenBy(Myself))
		RemoveSpellRES("rr#spwr2") // remove one instance of the spell upon casting
END

IF
	HaveSpellRES("rr#spwr2")
    !GlobalTimerNotExpired("rr#web","LOCALS") // Web refresh timer
	OR(3)
	See([EVILCUTOFF.0.107])
	See([EVILCUTOFF.0.108])
	!See([EVILCUTOFF])
	See(NinthNearest([GOODCUTOFF]))
	!Race(LastSeenBy(Myself),ELEMENTAL)
	!Race(LastSeenBy(Myself),SHADOW)
	!Race(LastSeenBy(Myself),SPECTRE)
	!Race(LastSeenBy(Myself),MIST)
	!Race(LastSeenBy(Myself),WRAITH)
	!Race(LastSeenBy(Myself),SLIME)
	!Race(LastSeenBy(Myself),DRAGON)
	!Class(LastSeenBy(Myself),GIANT)
	!Class(LastSeenBy(Myself),GOLEM_IRON)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTCOLD)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)  // Spell Immunity: Alteration
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!CheckStatGT(LastSeenBy(Myself),0,WEB)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!Check%State%(LastSeenBy(Myself),%Num%ITEM_HOLD)
THEN
	RESPONSE #100
		SetGlobalTimer("rr#web","LOCALS",30)  // web refresh timer
        ReallyForceSpellRes("rr#spwr2",LastSeenBy(Myself))
		RemoveSpellRES("rr#spwr2") // remove one instance of the spell upon casting
END

IF
	HaveSpellRES("rr#spwr2")
    !GlobalTimerNotExpired("rr#web","LOCALS") // Web refresh timer
	OR(3)
	See([EVILCUTOFF.0.107])
	See([EVILCUTOFF.0.108])
	!See([EVILCUTOFF])
	See(TenthNearest([GOODCUTOFF]))
	!Race(LastSeenBy(Myself),ELEMENTAL)
	!Race(LastSeenBy(Myself),SHADOW)
	!Race(LastSeenBy(Myself),SPECTRE)
	!Race(LastSeenBy(Myself),MIST)
	!Race(LastSeenBy(Myself),WRAITH)
	!Race(LastSeenBy(Myself),SLIME)
	!Race(LastSeenBy(Myself),DRAGON)
	!Class(LastSeenBy(Myself),GIANT)
	!Class(LastSeenBy(Myself),GOLEM_IRON)
	!StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
	CheckStatLT(LastSeenBy(Myself),50,RESISTCOLD)
	CheckStatGT(LastSeenBy(Myself),0,SAVEVSSPELL)
	!CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
	!CheckStat(LastSeenBy(Myself),8,WIZARD_SPELL_IMMUNITY)  // Spell Immunity: Alteration
	!CheckStatGT(LastSeenBy(Myself),0,MINORGLOBE)
	!CheckStatGT(LastSeenBy(Myself),0,HELD)
	!CheckStatGT(LastSeenBy(Myself),0,WEB)
	!HasItemEquiped("MISC73",LastSeenBy(Myself)) // The Horn of Kazgaroth
	!Check%State%(LastSeenBy(Myself),%Num%ITEM_HOLD)
THEN
	RESPONSE #100
		SetGlobalTimer("rr#web","LOCALS",30)  // web refresh timer
        ReallyForceSpellRes("rr#spwr2",LastSeenBy(Myself))
		RemoveSpellRES("rr#spwr2") // remove one instance of the spell upon casting
END

IF
See(NearestEnemyOf(Myself))
CheckStatGT(LastSeenBy(Myself),0,WEB)
!StateCheck(LastSeenBy(Myself),STATE_POISONED)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(LastSeenBy(Myself),15)
END

IF
See(SecondNearestEnemyOf(Myself))
CheckStatGT(LastSeenBy(Myself),0,WEB)
!StateCheck(LastSeenBy(Myself),STATE_POISONED)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(LastSeenBy(Myself),15)
END

IF
See(ThirdNearestEnemyOf(Myself))
CheckStatGT(LastSeenBy(Myself),0,WEB)
!StateCheck(LastSeenBy(Myself),STATE_POISONED)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(LastSeenBy(Myself),15)
END

IF
See(FourthNearestEnemyOf(Myself))
CheckStatGT(LastSeenBy(Myself),0,WEB)
!StateCheck(LastSeenBy(Myself),STATE_POISONED)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(LastSeenBy(Myself),15)
END

IF
See(FifthNearestEnemyOf(Myself))
CheckStatGT(LastSeenBy(Myself),0,WEB)
!StateCheck(LastSeenBy(Myself),STATE_POISONED)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(LastSeenBy(Myself),15)
END

IF
See(SixthNearestEnemyOf(Myself))
CheckStatGT(LastSeenBy(Myself),0,WEB)
!StateCheck(LastSeenBy(Myself),STATE_POISONED)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(LastSeenBy(Myself),15)
END

IF
See([PC.0.0.MAGE])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.MAGE],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.MAGE])
CheckStatLT([PC.0.0.MAGE],50,RESISTPIERCING)
!CheckStatGT([PC.0.0.MAGE],0,STONESKINS)
!StateCheck([PC.0.0.MAGE],STATE_MIRRORIMAGE)
!StateCheck([PC.0.0.MAGE],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.MAGE],EVILCUTOFF)
HPPercentLT([PC.0.0.MAGE],25)
Range([PC.0.0.MAGE],5)
THEN
RESPONSE #75
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.MAGE],30)
RESPONSE #25
Continue()
END

IF
See([PC.0.0.MAGE_THIEF])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.MAGE_THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.MAGE_THIEF])
CheckStatLT([PC.0.0.MAGE_THIEF],50,RESISTPIERCING)
!CheckStatGT([PC.0.0.MAGE_THIEF],0,STONESKINS)
!StateCheck([PC.0.0.MAGE_THIEF],STATE_MIRRORIMAGE)
!StateCheck([PC.0.0.MAGE_THIEF],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.MAGE_THIEF],EVILCUTOFF)
HPPercentLT([PC.0.0.MAGE_THIEF],25)
Range([PC.0.0.MAGE_THIEF],5)
THEN
RESPONSE #75
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.MAGE_THIEF],30)
RESPONSE #25
Continue()
END

IF
See([PC.0.0.THIEF])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.THIEF])
CheckStatLT([PC.0.0.THIEF],50,RESISTPIERCING)
!CheckStatGT([PC.0.0.THIEF],0,STONESKINS)
!StateCheck([PC.0.0.THIEF],STATE_MIRRORIMAGE)
!StateCheck([PC.0.0.THIEF],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.THIEF],EVILCUTOFF)
HPPercentLT([PC.0.0.THIEF],25)
Range([PC.0.0.THIEF],5)
THEN
RESPONSE #60
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.THIEF],30)
RESPONSE #40
Continue()
END

IF
See([PC.0.0.BARD])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.BARD],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.BARD])
CheckStatLT([PC.0.0.BARD],50,RESISTPIERCING)
!CheckStatGT([PC.0.0.BARD],0,STONESKINS)
!StateCheck([PC.0.0.BARD],STATE_MIRRORIMAGE)
!StateCheck([PC.0.0.BARD],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.BARD],EVILCUTOFF)
HPPercentLT([PC.0.0.BARD],25)
Range([PC.0.0.BARD],5)
THEN
RESPONSE #60
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.BARD],30)
RESPONSE #40
Continue()
END

IF
See(NearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(NearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",NearestEnemyOf(Myself))
CheckStatLT(NearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(NearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
!StateCheck(NearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(NearestEnemyOf(Myself),EVILCUTOFF)
HPPercentLT(NearestEnemyOf(Myself),25)
Range(NearestEnemyOf(Myself),5)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(NearestEnemyOf(Myself),15)
END

IF
See(SecondNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(SecondNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",SecondNearestEnemyOf(Myself))
CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(SecondNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
!StateCheck(SecondNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(SecondNearestEnemyOf(Myself),EVILCUTOFF)
HPPercentLT(SecondNearestEnemyOf(Myself),25)
Range(SecondNearestEnemyOf(Myself),5)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(SecondNearestEnemyOf(Myself),15)
END

IF
See(ThirdNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(ThirdNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",ThirdNearestEnemyOf(Myself))
CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(ThirdNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
!StateCheck(ThirdNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(ThirdNearestEnemyOf(Myself),EVILCUTOFF)
HPPercentLT(ThirdNearestEnemyOf(Myself),25)
Range(ThirdNearestEnemyOf(Myself),5)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(ThirdNearestEnemyOf(Myself),15)
END

IF
See(FourthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(FourthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",FourthNearestEnemyOf(Myself))
CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(FourthNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
!StateCheck(FourthNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(FourthNearestEnemyOf(Myself),EVILCUTOFF)
HPPercentLT(FourthNearestEnemyOf(Myself),25)
Range(FourthNearestEnemyOf(Myself),5)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(FourthNearestEnemyOf(Myself),15)
END

IF
See(FifthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(FifthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",FifthNearestEnemyOf(Myself))
CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(FifthNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
!StateCheck(FifthNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(FifthNearestEnemyOf(Myself),EVILCUTOFF)
HPPercentLT(FifthNearestEnemyOf(Myself),25)
Range(FifthNearestEnemyOf(Myself),5)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(FifthNearestEnemyOf(Myself),15)
END

IF
See(SixthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(SixthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",SixthNearestEnemyOf(Myself))
CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(SixthNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
!StateCheck(SixthNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(SixthNearestEnemyOf(Myself),EVILCUTOFF)
HPPercentLT(SixthNearestEnemyOf(Myself),25)
Range(SixthNearestEnemyOf(Myself),5)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(SixthNearestEnemyOf(Myself),15)
END

IF
See([PC.0.0.MAGE])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.MAGE],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.MAGE])
CheckStatLT([PC.0.0.MAGE],50,RESISTPIERCING)
!CheckStatGT([PC.0.0.MAGE],0,STONESKINS)
!StateCheck([PC.0.0.MAGE],STATE_MIRRORIMAGE)
!StateCheck([PC.0.0.MAGE],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.MAGE],EVILCUTOFF)
HPPercentLT([PC.0.0.MAGE],25)
THEN
RESPONSE #75
MoveToObject([PC.0.0.MAGE])
RESPONSE #25
Continue()
END

IF
See([PC.0.0.MAGE_THIEF])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.MAGE_THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.MAGE_THIEF])
CheckStatLT([PC.0.0.MAGE_THIEF],50,RESISTPIERCING)
!CheckStatGT([PC.0.0.MAGE_THIEF],0,STONESKINS)
!StateCheck([PC.0.0.MAGE_THIEF],STATE_MIRRORIMAGE)
!StateCheck([PC.0.0.MAGE_THIEF],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.MAGE_THIEF],EVILCUTOFF)
HPPercentLT([PC.0.0.MAGE_THIEF],25)
THEN
RESPONSE #75
MoveToObject([PC.0.0.MAGE_THIEF])
RESPONSE #25
Continue()
END

IF
See([PC.0.0.THIEF])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.THIEF])
CheckStatLT([PC.0.0.THIEF],50,RESISTPIERCING)
!CheckStatGT([PC.0.0.THIEF],0,STONESKINS)
!StateCheck([PC.0.0.THIEF],STATE_MIRRORIMAGE)
!StateCheck([PC.0.0.THIEF],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.THIEF],EVILCUTOFF)
HPPercentLT([PC.0.0.THIEF],25)
THEN
RESPONSE #60
MoveToObject([PC.0.0.THIEF])
RESPONSE #40
Continue()
END

IF
See([PC.0.0.BARD])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.BARD],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.BARD])
CheckStatLT([PC.0.0.BARD],50,RESISTPIERCING)
!CheckStatGT([PC.0.0.BARD],0,STONESKINS)
!StateCheck([PC.0.0.BARD],STATE_MIRRORIMAGE)
!StateCheck([PC.0.0.BARD],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.BARD],EVILCUTOFF)
HPPercentLT([PC.0.0.BARD],25)
THEN
RESPONSE #60
MoveToObject([PC.0.0.BARD])
RESPONSE #40
Continue()
END

IF
See(NearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(NearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",NearestEnemyOf(Myself))
CheckStatLT(NearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(NearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
!StateCheck(NearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(NearestEnemyOf(Myself),EVILCUTOFF)
HPPercentLT(NearestEnemyOf(Myself),25)
THEN
RESPONSE #100
MoveToObject(NearestEnemyOf(Myself))
END

IF
See(SecondNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(SecondNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",SecondNearestEnemyOf(Myself))
CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(SecondNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
!StateCheck(SecondNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(SecondNearestEnemyOf(Myself),EVILCUTOFF)
HPPercentLT(SecondNearestEnemyOf(Myself),25)
THEN
RESPONSE #100
MoveToObject(SecondNearestEnemyOf(Myself))
END

IF
See(ThirdNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(ThirdNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",ThirdNearestEnemyOf(Myself))
CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(ThirdNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
!StateCheck(ThirdNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(ThirdNearestEnemyOf(Myself),EVILCUTOFF)
HPPercentLT(ThirdNearestEnemyOf(Myself),25)
THEN
RESPONSE #100
MoveToObject(ThirdNearestEnemyOf(Myself))
END

IF
See(FourthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(FourthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",FourthNearestEnemyOf(Myself))
CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(FourthNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
!StateCheck(FourthNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(FourthNearestEnemyOf(Myself),EVILCUTOFF)
HPPercentLT(FourthNearestEnemyOf(Myself),25)
THEN
RESPONSE #100
MoveToObject(FourthNearestEnemyOf(Myself))
END

IF
See(FifthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(FifthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",FifthNearestEnemyOf(Myself))
CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(FifthNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
!StateCheck(FifthNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(FifthNearestEnemyOf(Myself),EVILCUTOFF)
HPPercentLT(FifthNearestEnemyOf(Myself),25)
THEN
RESPONSE #100
MoveToObject(FifthNearestEnemyOf(Myself))
END

IF
See(SixthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(SixthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",SixthNearestEnemyOf(Myself))
CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(SixthNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
!StateCheck(SixthNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(SixthNearestEnemyOf(Myself),EVILCUTOFF)
HPPercentLT(SixthNearestEnemyOf(Myself),25)
THEN
RESPONSE #100
MoveToObject(SixthNearestEnemyOf(Myself))
END

IF
See([PC.0.0.MAGE])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.MAGE],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.MAGE])
CheckStatLT([PC.0.0.MAGE],50,RESISTPIERCING)
!CheckStatGT([PC.0.0.MAGE],0,STONESKINS)
!StateCheck([PC.0.0.MAGE],STATE_MIRRORIMAGE)
!StateCheck([PC.0.0.MAGE],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.MAGE],EVILCUTOFF)
Range([PC.0.0.MAGE],5)
THEN
RESPONSE #75
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.MAGE],30)
RESPONSE #25
Continue()
END

IF
See([PC.0.0.MAGE_THIEF])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.MAGE_THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.MAGE_THIEF])
CheckStatLT([PC.0.0.MAGE_THIEF],50,RESISTPIERCING)
!CheckStatGT([PC.0.0.MAGE_THIEF],0,STONESKINS)
!StateCheck([PC.0.0.MAGE_THIEF],STATE_MIRRORIMAGE)
!StateCheck([PC.0.0.MAGE_THIEF],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.MAGE_THIEF],EVILCUTOFF)
Range([PC.0.0.MAGE_THIEF],5)
THEN
RESPONSE #75
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.MAGE_THIEF],30)
RESPONSE #25
Continue()
END

IF
See([PC.0.0.THIEF])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.THIEF])
CheckStatLT([PC.0.0.THIEF],50,RESISTPIERCING)
!CheckStatGT([PC.0.0.THIEF],0,STONESKINS)
!StateCheck([PC.0.0.THIEF],STATE_MIRRORIMAGE)
!StateCheck([PC.0.0.THIEF],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.THIEF],EVILCUTOFF)
Range([PC.0.0.THIEF],5)
THEN
RESPONSE #60
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.THIEF],30)
RESPONSE #40
Continue()
END

IF
See([PC.0.0.BARD])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.BARD],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.BARD])
CheckStatLT([PC.0.0.BARD],50,RESISTPIERCING)
!CheckStatGT([PC.0.0.BARD],0,STONESKINS)
!StateCheck([PC.0.0.BARD],STATE_MIRRORIMAGE)
!StateCheck([PC.0.0.BARD],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.BARD],EVILCUTOFF)
Range([PC.0.0.BARD],5)
THEN
RESPONSE #60
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.BARD],30)
RESPONSE #40
Continue()
END

IF
See(NearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(NearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",NearestEnemyOf(Myself))
CheckStatLT(NearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(NearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
!StateCheck(NearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(NearestEnemyOf(Myself),EVILCUTOFF)
Range(NearestEnemyOf(Myself),5)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(NearestEnemyOf(Myself),15)
END

IF
See(SecondNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(SecondNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",SecondNearestEnemyOf(Myself))
CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(SecondNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
!StateCheck(SecondNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(SecondNearestEnemyOf(Myself),EVILCUTOFF)
Range(SecondNearestEnemyOf(Myself),5)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(SecondNearestEnemyOf(Myself),15)
END

IF
See(ThirdNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(ThirdNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",ThirdNearestEnemyOf(Myself))
CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(ThirdNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
!StateCheck(ThirdNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(ThirdNearestEnemyOf(Myself),EVILCUTOFF)
Range(ThirdNearestEnemyOf(Myself),5)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(ThirdNearestEnemyOf(Myself),15)
END

IF
See(FourthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(FourthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",FourthNearestEnemyOf(Myself))
CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(FourthNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
!StateCheck(FourthNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(FourthNearestEnemyOf(Myself),EVILCUTOFF)
Range(FourthNearestEnemyOf(Myself),5)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(FourthNearestEnemyOf(Myself),15)
END

IF
See(FifthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(FifthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",FifthNearestEnemyOf(Myself))
CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(FifthNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
!StateCheck(FifthNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(FifthNearestEnemyOf(Myself),EVILCUTOFF)
Range(FifthNearestEnemyOf(Myself),5)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(FifthNearestEnemyOf(Myself),15)
END

IF
See(SixthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(SixthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",SixthNearestEnemyOf(Myself))
CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(SixthNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
!StateCheck(SixthNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(SixthNearestEnemyOf(Myself),EVILCUTOFF)
Range(SixthNearestEnemyOf(Myself),5)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(SixthNearestEnemyOf(Myself),15)
END

IF
See([PC.0.0.MAGE])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.MAGE],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.MAGE])
CheckStatLT([PC.0.0.MAGE],50,RESISTPIERCING)
!CheckStatGT([PC.0.0.MAGE],0,STONESKINS)
!StateCheck([PC.0.0.MAGE],STATE_MIRRORIMAGE)
!StateCheck([PC.0.0.MAGE],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.MAGE],EVILCUTOFF)
THEN
RESPONSE #75
MoveToObject([PC.0.0.MAGE])
RESPONSE #25
Continue()
END

IF
See([PC.0.0.MAGE_THIEF])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.MAGE_THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.MAGE_THIEF])
CheckStatLT([PC.0.0.MAGE_THIEF],50,RESISTPIERCING)
!CheckStatGT([PC.0.0.MAGE_THIEF],0,STONESKINS)
!StateCheck([PC.0.0.MAGE_THIEF],STATE_MIRRORIMAGE)
!StateCheck([PC.0.0.MAGE_THIEF],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.MAGE_THIEF],EVILCUTOFF)
THEN
RESPONSE #75
MoveToObject([PC.0.0.MAGE_THIEF])
RESPONSE #25
Continue()
END

IF
See([PC.0.0.THIEF])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.THIEF])
CheckStatLT([PC.0.0.THIEF],50,RESISTPIERCING)
!CheckStatGT([PC.0.0.THIEF],0,STONESKINS)
!StateCheck([PC.0.0.THIEF],STATE_MIRRORIMAGE)
!StateCheck([PC.0.0.THIEF],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.THIEF],EVILCUTOFF)
THEN
RESPONSE #60
MoveToObject([PC.0.0.THIEF])
RESPONSE #40
Continue()
END

IF
See([PC.0.0.BARD])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.BARD],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.BARD])
CheckStatLT([PC.0.0.BARD],50,RESISTPIERCING)
!CheckStatGT([PC.0.0.BARD],0,STONESKINS)
!StateCheck([PC.0.0.BARD],STATE_MIRRORIMAGE)
!StateCheck([PC.0.0.BARD],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.BARD],EVILCUTOFF)
THEN
RESPONSE #60
MoveToObject([PC.0.0.BARD])
RESPONSE #40
Continue()
END

IF
See(NearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(NearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",NearestEnemyOf(Myself))
CheckStatLT(NearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(NearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(NearestEnemyOf(Myself),STATE_MIRRORIMAGE)
!StateCheck(NearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(NearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
MoveToObject(NearestEnemyOf(Myself))
END

IF
See(SecondNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(SecondNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",SecondNearestEnemyOf(Myself))
CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(SecondNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(SecondNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
!StateCheck(SecondNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(SecondNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
MoveToObject(SecondNearestEnemyOf(Myself))
END

IF
See(ThirdNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(ThirdNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",ThirdNearestEnemyOf(Myself))
CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(ThirdNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(ThirdNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
!StateCheck(ThirdNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(ThirdNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
MoveToObject(ThirdNearestEnemyOf(Myself))
END

IF
See(FourthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(FourthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",FourthNearestEnemyOf(Myself))
CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(FourthNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(FourthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
!StateCheck(FourthNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(FourthNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
MoveToObject(FourthNearestEnemyOf(Myself))
END

IF
See(FifthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(FifthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",FifthNearestEnemyOf(Myself))
CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(FifthNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(FifthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
!StateCheck(FifthNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(FifthNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
MoveToObject(FifthNearestEnemyOf(Myself))
END

IF
See(SixthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(SixthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",SixthNearestEnemyOf(Myself))
CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(SixthNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(SixthNearestEnemyOf(Myself),STATE_MIRRORIMAGE)
!StateCheck(SixthNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(SixthNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
MoveToObject(SixthNearestEnemyOf(Myself))
END

IF
See([PC.0.0.MAGE])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.MAGE],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.MAGE])
CheckStatLT([PC.0.0.MAGE],50,RESISTPIERCING)
!CheckStatGT([PC.0.0.MAGE],0,STONESKINS)
!StateCheck([PC.0.0.MAGE],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.MAGE],EVILCUTOFF)
Range([PC.0.0.MAGE],5)
THEN
RESPONSE #75
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.MAGE],30)
RESPONSE #25
Continue()
END

IF
See([PC.0.0.MAGE_THIEF])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.MAGE_THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.MAGE_THIEF])
CheckStatLT([PC.0.0.MAGE_THIEF],50,RESISTPIERCING)
!CheckStatGT([PC.0.0.MAGE_THIEF],0,STONESKINS)
!StateCheck([PC.0.0.MAGE_THIEF],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.MAGE_THIEF],EVILCUTOFF)
Range([PC.0.0.MAGE_THIEF],5)
THEN
RESPONSE #75
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.MAGE_THIEF],30)
RESPONSE #25
Continue()
END

IF
See([PC.0.0.THIEF])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.THIEF])
CheckStatLT([PC.0.0.THIEF],50,RESISTPIERCING)
!CheckStatGT([PC.0.0.THIEF],0,STONESKINS)
!StateCheck([PC.0.0.THIEF],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.THIEF],EVILCUTOFF)
Range([PC.0.0.THIEF],5)
THEN
RESPONSE #60
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.THIEF],30)
RESPONSE #40
Continue()
END

IF
See([PC.0.0.BARD])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.BARD],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.BARD])
CheckStatLT([PC.0.0.BARD],50,RESISTPIERCING)
!CheckStatGT([PC.0.0.BARD],0,STONESKINS)
!StateCheck([PC.0.0.BARD],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.BARD],EVILCUTOFF)
Range([PC.0.0.BARD],5)
THEN
RESPONSE #60
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.BARD],30)
RESPONSE #40
Continue()
END

IF
See(NearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(NearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",NearestEnemyOf(Myself))
CheckStatLT(NearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(NearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(NearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(NearestEnemyOf(Myself),EVILCUTOFF)
Range(NearestEnemyOf(Myself),5)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(NearestEnemyOf(Myself),15)
END

IF
See(SecondNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(SecondNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",SecondNearestEnemyOf(Myself))
CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(SecondNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(SecondNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(SecondNearestEnemyOf(Myself),EVILCUTOFF)
Range(SecondNearestEnemyOf(Myself),5)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(SecondNearestEnemyOf(Myself),15)
END

IF
See(ThirdNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(ThirdNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",ThirdNearestEnemyOf(Myself))
CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(ThirdNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(ThirdNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(ThirdNearestEnemyOf(Myself),EVILCUTOFF)
Range(ThirdNearestEnemyOf(Myself),5)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(ThirdNearestEnemyOf(Myself),15)
END

IF
See(FourthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(FourthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",FourthNearestEnemyOf(Myself))
CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(FourthNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(FourthNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(FourthNearestEnemyOf(Myself),EVILCUTOFF)
Range(FourthNearestEnemyOf(Myself),5)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(FourthNearestEnemyOf(Myself),15)
END

IF
See(FifthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(FifthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",FifthNearestEnemyOf(Myself))
CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(FifthNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(FifthNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(FifthNearestEnemyOf(Myself),EVILCUTOFF)
Range(FifthNearestEnemyOf(Myself),5)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(FifthNearestEnemyOf(Myself),15)
END

IF
See(SixthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(SixthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",SixthNearestEnemyOf(Myself))
CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(SixthNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(SixthNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(SixthNearestEnemyOf(Myself),EVILCUTOFF)
Range(SixthNearestEnemyOf(Myself),5)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(SixthNearestEnemyOf(Myself),15)
END

IF
See([PC.0.0.MAGE])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.MAGE],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.MAGE])
CheckStatLT([PC.0.0.MAGE],50,RESISTPIERCING)
!CheckStatGT([PC.0.0.MAGE],0,STONESKINS)
!StateCheck([PC.0.0.MAGE],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.MAGE],EVILCUTOFF)
THEN
RESPONSE #75
MoveToObject([PC.0.0.MAGE])
RESPONSE #25
Continue()
END

IF
See([PC.0.0.MAGE_THIEF])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.MAGE_THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.MAGE_THIEF])
CheckStatLT([PC.0.0.MAGE_THIEF],50,RESISTPIERCING)
!CheckStatGT([PC.0.0.MAGE_THIEF],0,STONESKINS)
!StateCheck([PC.0.0.MAGE_THIEF],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.MAGE_THIEF],EVILCUTOFF)
THEN
RESPONSE #75
MoveToObject([PC.0.0.MAGE_THIEF])
RESPONSE #25
Continue()
END

IF
See([PC.0.0.THIEF])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.THIEF])
CheckStatLT([PC.0.0.THIEF],50,RESISTPIERCING)
!CheckStatGT([PC.0.0.THIEF],0,STONESKINS)
!StateCheck([PC.0.0.THIEF],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.THIEF],EVILCUTOFF)
THEN
RESPONSE #60
MoveToObject([PC.0.0.THIEF])
RESPONSE #40
Continue()
END

IF
See([PC.0.0.BARD])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.BARD],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.BARD])
CheckStatLT([PC.0.0.BARD],50,RESISTPIERCING)
!CheckStatGT([PC.0.0.BARD],0,STONESKINS)
!StateCheck([PC.0.0.BARD],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.BARD],EVILCUTOFF)
THEN
RESPONSE #60
MoveToObject([PC.0.0.BARD])
RESPONSE #40
Continue()
END

IF
See(NearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(NearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",NearestEnemyOf(Myself))
CheckStatLT(NearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(NearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(NearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(NearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
MoveToObject(NearestEnemyOf(Myself))
END

IF
See(SecondNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(SecondNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",SecondNearestEnemyOf(Myself))
CheckStatLT(SecondNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(SecondNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(SecondNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(SecondNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
MoveToObject(SecondNearestEnemyOf(Myself))
END

IF
See(ThirdNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(ThirdNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",ThirdNearestEnemyOf(Myself))
CheckStatLT(ThirdNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(ThirdNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(ThirdNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(ThirdNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
MoveToObject(ThirdNearestEnemyOf(Myself))
END

IF
See(FourthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(FourthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",FourthNearestEnemyOf(Myself))
CheckStatLT(FourthNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(FourthNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(FourthNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(FourthNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
MoveToObject(FourthNearestEnemyOf(Myself))
END

IF
See(FifthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(FifthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",FifthNearestEnemyOf(Myself))
CheckStatLT(FifthNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(FifthNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(FifthNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(FifthNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
MoveToObject(FifthNearestEnemyOf(Myself))
END

IF
See(SixthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(SixthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",SixthNearestEnemyOf(Myself))
CheckStatLT(SixthNearestEnemyOf(Myself),50,RESISTPIERCING)
!CheckStatGT(SixthNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(SixthNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(SixthNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
MoveToObject(SixthNearestEnemyOf(Myself))
END

IF
See([PC.0.0.MAGE])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.MAGE],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.MAGE])
!CheckStatGT([PC.0.0.MAGE],75,RESISTPIERCING)
!CheckStatGT([PC.0.0.MAGE],0,STONESKINS)
!StateCheck([PC.0.0.MAGE],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.MAGE],EVILCUTOFF)
Range([PC.0.0.MAGE],5)
THEN
RESPONSE #75
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.MAGE],30)
RESPONSE #25
Continue()
END

IF
See([PC.0.0.MAGE_THIEF])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.MAGE_THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.MAGE_THIEF])
!CheckStatGT([PC.0.0.MAGE_THIEF],75,RESISTPIERCING)
!CheckStatGT([PC.0.0.MAGE_THIEF],0,STONESKINS)
!StateCheck([PC.0.0.MAGE_THIEF],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.MAGE_THIEF],EVILCUTOFF)
Range([PC.0.0.MAGE_THIEF],5)
THEN
RESPONSE #75
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.MAGE_THIEF],30)
RESPONSE #25
Continue()
END

IF
See([PC.0.0.THIEF])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.THIEF])
!CheckStatGT([PC.0.0.THIEF],75,RESISTPIERCING)
!CheckStatGT([PC.0.0.THIEF],0,STONESKINS)
!StateCheck([PC.0.0.THIEF],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.THIEF],EVILCUTOFF)
Range([PC.0.0.THIEF],5)
THEN
RESPONSE #60
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.THIEF],30)
RESPONSE #40
Continue()
END

IF
See([PC.0.0.BARD])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.BARD],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.BARD])
!CheckStatGT([PC.0.0.BARD],75,RESISTPIERCING)
!CheckStatGT([PC.0.0.BARD],0,STONESKINS)
!StateCheck([PC.0.0.BARD],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.BARD],EVILCUTOFF)
Range([PC.0.0.BARD],5)
THEN
RESPONSE #60
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.BARD],30)
RESPONSE #40
Continue()
END

IF
See(NearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(NearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",NearestEnemyOf(Myself))
!CheckStatGT(NearestEnemyOf(Myself),75,RESISTPIERCING)
!CheckStatGT(NearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(NearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(NearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(NearestEnemyOf(Myself),15)
END

IF
See(SecondNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(SecondNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",SecondNearestEnemyOf(Myself))
!CheckStatGT(SecondNearestEnemyOf(Myself),75,RESISTPIERCING)
!CheckStatGT(SecondNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(SecondNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(SecondNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(SecondNearestEnemyOf(Myself),15)
END

IF
See(ThirdNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(ThirdNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",ThirdNearestEnemyOf(Myself))
!CheckStatGT(ThirdNearestEnemyOf(Myself),75,RESISTPIERCING)
!CheckStatGT(ThirdNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(ThirdNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(ThirdNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(ThirdNearestEnemyOf(Myself),15)
END

IF
See(FourthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(FourthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",FourthNearestEnemyOf(Myself))
!CheckStatGT(FourthNearestEnemyOf(Myself),75,RESISTPIERCING)
!CheckStatGT(FourthNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(FourthNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(FourthNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(FourthNearestEnemyOf(Myself),15)
END

IF
See(FifthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(FifthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",FifthNearestEnemyOf(Myself))
!CheckStatGT(FifthNearestEnemyOf(Myself),75,RESISTPIERCING)
!CheckStatGT(FifthNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(FifthNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(FifthNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(FifthNearestEnemyOf(Myself),15)
END

IF
See(SixthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(SixthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",SixthNearestEnemyOf(Myself))
!CheckStatGT(SixthNearestEnemyOf(Myself),75,RESISTPIERCING)
!CheckStatGT(SixthNearestEnemyOf(Myself),0,STONESKINS)
!StateCheck(SixthNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(SixthNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(SixthNearestEnemyOf(Myself),15)
END

IF
See([PC.0.0.MAGE])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.MAGE],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.MAGE])
!CheckStatGT([PC.0.0.MAGE],75,RESISTPIERCING)
!StateCheck([PC.0.0.MAGE],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.MAGE],EVILCUTOFF)
Range([PC.0.0.MAGE],5)
THEN
RESPONSE #75
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.MAGE],30)
RESPONSE #25
Continue()
END

IF
See([PC.0.0.MAGE_THIEF])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.MAGE_THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.MAGE_THIEF])
!CheckStatGT([PC.0.0.MAGE_THIEF],75,RESISTPIERCING)
!StateCheck([PC.0.0.MAGE_THIEF],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.MAGE_THIEF],EVILCUTOFF)
Range([PC.0.0.MAGE_THIEF],5)
THEN
RESPONSE #75
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.MAGE_THIEF],30)
RESPONSE #25
Continue()
END

IF
See([PC.0.0.THIEF])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.THIEF])
!CheckStatGT([PC.0.0.THIEF],75,RESISTPIERCING)
!StateCheck([PC.0.0.THIEF],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.THIEF],EVILCUTOFF)
Range([PC.0.0.THIEF],5)
THEN
RESPONSE #60
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.THIEF],30)
RESPONSE #40
Continue()
END

IF
See([PC.0.0.BARD])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.BARD],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.BARD])
!CheckStatGT([PC.0.0.BARD],75,RESISTPIERCING)
!StateCheck([PC.0.0.BARD],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.BARD],EVILCUTOFF)
Range([PC.0.0.BARD],5)
THEN
RESPONSE #60
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.BARD],30)
RESPONSE #40
Continue()
END

IF
See(NearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(NearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",NearestEnemyOf(Myself))
!CheckStatGT(NearestEnemyOf(Myself),75,RESISTPIERCING)
!StateCheck(NearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(NearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(NearestEnemyOf(Myself),15)
END

IF
See(SecondNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(SecondNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",SecondNearestEnemyOf(Myself))
!CheckStatGT(SecondNearestEnemyOf(Myself),75,RESISTPIERCING)
!StateCheck(SecondNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(SecondNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(SecondNearestEnemyOf(Myself),15)
END

IF
See(ThirdNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(ThirdNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",ThirdNearestEnemyOf(Myself))
!CheckStatGT(ThirdNearestEnemyOf(Myself),75,RESISTPIERCING)
!StateCheck(ThirdNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(ThirdNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(ThirdNearestEnemyOf(Myself),15)
END

IF
See(FourthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(FourthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",FourthNearestEnemyOf(Myself))
!CheckStatGT(FourthNearestEnemyOf(Myself),75,RESISTPIERCING)
!StateCheck(FourthNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(FourthNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(FourthNearestEnemyOf(Myself),15)
END

IF
See(FifthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(FifthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",FifthNearestEnemyOf(Myself))
!CheckStatGT(FifthNearestEnemyOf(Myself),75,RESISTPIERCING)
!StateCheck(FifthNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(FifthNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(FifthNearestEnemyOf(Myself),15)
END

IF
See(SixthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(SixthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",SixthNearestEnemyOf(Myself))
!CheckStatGT(SixthNearestEnemyOf(Myself),75,RESISTPIERCING)
!StateCheck(SixthNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(SixthNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(SixthNearestEnemyOf(Myself),15)
END

IF
See([PC.0.0.MAGE])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.MAGE],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.MAGE])
!CheckStatGT([PC.0.0.MAGE],99,RESISTPIERCING)
!StateCheck([PC.0.0.MAGE],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.MAGE],EVILCUTOFF)
Range([PC.0.0.MAGE],5)
THEN
RESPONSE #75
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.MAGE],30)
RESPONSE #25
Continue()
END

IF
See([PC.0.0.MAGE_THIEF])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.MAGE_THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.MAGE_THIEF])
!CheckStatGT([PC.0.0.MAGE_THIEF],99,RESISTPIERCING)
!StateCheck([PC.0.0.MAGE_THIEF],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.MAGE_THIEF],EVILCUTOFF)
Range([PC.0.0.MAGE_THIEF],5)
THEN
RESPONSE #75
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.MAGE_THIEF],30)
RESPONSE #25
Continue()
END

IF
See([PC.0.0.THIEF])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.THIEF])
!CheckStatGT([PC.0.0.THIEF],99,RESISTPIERCING)
!StateCheck([PC.0.0.THIEF],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.THIEF],EVILCUTOFF)
Range([PC.0.0.THIEF],5)
THEN
RESPONSE #60
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.THIEF],30)
RESPONSE #40
Continue()
END

IF
See([PC.0.0.BARD])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.BARD],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.BARD])
!CheckStatGT([PC.0.0.BARD],99,RESISTPIERCING)
!StateCheck([PC.0.0.BARD],STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.BARD],EVILCUTOFF)
Range([PC.0.0.BARD],5)
THEN
RESPONSE #60
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.BARD],30)
RESPONSE #40
Continue()
END

IF
See(NearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(NearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",NearestEnemyOf(Myself))
!CheckStatGT(NearestEnemyOf(Myself),99,RESISTPIERCING)
!StateCheck(NearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(NearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(NearestEnemyOf(Myself),15)
END

IF
See(SecondNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(SecondNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",SecondNearestEnemyOf(Myself))
!CheckStatGT(SecondNearestEnemyOf(Myself),99,RESISTPIERCING)
!StateCheck(SecondNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(SecondNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(SecondNearestEnemyOf(Myself),15)
END

IF
See(ThirdNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(ThirdNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",ThirdNearestEnemyOf(Myself))
!CheckStatGT(ThirdNearestEnemyOf(Myself),99,RESISTPIERCING)
!StateCheck(ThirdNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(ThirdNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(ThirdNearestEnemyOf(Myself),15)
END

IF
See(FourthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(FourthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",FourthNearestEnemyOf(Myself))
!CheckStatGT(FourthNearestEnemyOf(Myself),99,RESISTPIERCING)
!StateCheck(FourthNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(FourthNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(FourthNearestEnemyOf(Myself),15)
END

IF
See(FifthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(FifthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",FifthNearestEnemyOf(Myself))
!CheckStatGT(FifthNearestEnemyOf(Myself),99,RESISTPIERCING)
!StateCheck(FifthNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(FifthNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(FifthNearestEnemyOf(Myself),15)
END

IF
See(SixthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(SixthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",SixthNearestEnemyOf(Myself))
!CheckStatGT(SixthNearestEnemyOf(Myself),99,RESISTPIERCING)
!StateCheck(SixthNearestEnemyOf(Myself),STATE_STONE_DEATH)
Allegiance(Myself,ENEMY)
!Allegiance(SixthNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(SixthNearestEnemyOf(Myself),15)
END

IF
See([PC.0.0.MAGE])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.MAGE],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.MAGE])
!CheckStatGT([PC.0.0.MAGE],99,RESISTPIERCING)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.MAGE],EVILCUTOFF)
Range([PC.0.0.MAGE],5)
THEN
RESPONSE #75
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.MAGE],30)
RESPONSE #25
Continue()
END

IF
See([PC.0.0.MAGE_THIEF])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.MAGE_THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.MAGE_THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.MAGE_THIEF])
!CheckStatGT([PC.0.0.MAGE_THIEF],99,RESISTPIERCING)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.MAGE_THIEF],EVILCUTOFF)
Range([PC.0.0.MAGE_THIEF],5)
THEN
RESPONSE #75
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.MAGE_THIEF],30)
RESPONSE #25
Continue()
END

IF
See([PC.0.0.THIEF])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.THIEF],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.THIEF],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.THIEF])
!CheckStatGT([PC.0.0.THIEF],99,RESISTPIERCING)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.THIEF],EVILCUTOFF)
Range([PC.0.0.THIEF],5)
THEN
RESPONSE #60
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.THIEF],30)
RESPONSE #40
Continue()
END

IF
See([PC.0.0.BARD])
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat([PC.0.0.BARD],0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat([PC.0.0.BARD],3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",[PC.0.0.BARD])
!CheckStatGT([PC.0.0.BARD],99,RESISTPIERCING)
Allegiance(Myself,ENEMY)
!Allegiance([PC.0.0.BARD],EVILCUTOFF)
Range([PC.0.0.BARD],5)
THEN
RESPONSE #60
EquipMostDamagingMelee()
AttackReevaluate([PC.0.0.BARD],30)
RESPONSE #40
Continue()
END

IF
See(NearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(NearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(NearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",NearestEnemyOf(Myself))
!CheckStatGT(NearestEnemyOf(Myself),99,RESISTPIERCING)
Allegiance(Myself,ENEMY)
!Allegiance(NearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(NearestEnemyOf(Myself),15)
END

IF
See(SecondNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(SecondNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(SecondNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",SecondNearestEnemyOf(Myself))
!CheckStatGT(SecondNearestEnemyOf(Myself),99,RESISTPIERCING)
Allegiance(Myself,ENEMY)
!Allegiance(SecondNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(SecondNearestEnemyOf(Myself),15)
END

IF
See(ThirdNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(ThirdNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(ThirdNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",ThirdNearestEnemyOf(Myself))
!CheckStatGT(ThirdNearestEnemyOf(Myself),99,RESISTPIERCING)
Allegiance(Myself,ENEMY)
!Allegiance(ThirdNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(ThirdNearestEnemyOf(Myself),15)
END

IF
See(FourthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(FourthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(FourthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",FourthNearestEnemyOf(Myself))
!CheckStatGT(FourthNearestEnemyOf(Myself),99,RESISTPIERCING)
Allegiance(Myself,ENEMY)
!Allegiance(FourthNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(FourthNearestEnemyOf(Myself),15)
END

IF
See(FifthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(FifthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(FifthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",FifthNearestEnemyOf(Myself))
!CheckStatGT(FifthNearestEnemyOf(Myself),99,RESISTPIERCING)
Allegiance(Myself,ENEMY)
!Allegiance(FifthNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(FifthNearestEnemyOf(Myself),15)
END

IF
See(SixthNearestEnemyOf(Myself))
OR(2)
CheckStatGT(Myself,0,CLERIC_HALLOW)
CheckStat(SixthNearestEnemyOf(Myself),0,WIZARD_PROTECTION_FROM_NORMAL_WEAPONS)
OR(2)
CheckStat(Myself,0,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),4,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,2,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),1,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,3,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),2,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
OR(2)
CheckStatGT(Myself,5,CLERIC_HALLOW)
!CheckStat(SixthNearestEnemyOf(Myself),3,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
!HasItem("MORSWORD",SixthNearestEnemyOf(Myself))
!CheckStatGT(SixthNearestEnemyOf(Myself),99,RESISTPIERCING)
Allegiance(Myself,ENEMY)
!Allegiance(SixthNearestEnemyOf(Myself),EVILCUTOFF)
THEN
RESPONSE #100
EquipMostDamagingMelee()
AttackReevaluate(SixthNearestEnemyOf(Myself),15)
END

IF
    Allegiance(Myself,EVILCUTOFF) // only RandomWalk if hostile
	!GlobalTimerNotExpired("RR#Move","LOCALS")
	!Detect(NearestEnemyOf(Myself))
THEN
	RESPONSE #100
		RandomWalkContinuous()
END